AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GitradarArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gitradar-artifacts

  GitradarDatalakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gitradar-datalake

  TokenDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TokenDB
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  CodeMetricsDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CodeMetrics
      AttributeDefinitions:
        - AttributeName: metricId
          AttributeType: S
      KeySchema:
        - AttributeName: metricId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1



Outputs:
  GitradarArtifactsBucketName:
    Value: !Ref GitradarArtifactsBucket

  GitradarDatalakeBucketName:
    Value: !Ref GitradarDatalakeBucket

  TokenDatabaseName:
    Value: !Ref TokenDatabase

  CodeMetricsDatabaseName:
    Value: !Ref CodeMetricsDatabase
